config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :favorites, only: %i[create destroy]
  root to: "searches#index"
  resource :search, only: %i[index show]
  resources :users, only: %i[index show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :restaurant_name, presence: true
  validates :restaurant_address, uniqueness: { scope: [:user_id, :restaurant_name] }
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/ride.rb
class Ride < ApplicationRecord
  enum ride_area:{
     "":0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
     沖縄県:47
   }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true
  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username])
    end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    restaurant_name      = params["rest_name"]
    restaurant_address   = params["rest_add"]
    restaurant_latitude  = params["rest_lat"]
    restaurant_longitude = params["rest_lng"]
    favorite = current_user.favorites.build(restaurant_name: restaurant_name, restaurant_address: restaurant_address)
    @restaurant = { "name" => restaurant_name, "address" => restaurant_address, "latitude" => restaurant_latitude, "longitude" => restaurant_longitude }
    if favorite.save
      flash[:success] = "お気に入り登録しました。"
    else
      flash[:danger] = "お気に入り登録出来ませんでした。"
    end
    redirect_to search_url(rest: @restaurant)
  end

  def destroy
    restaurant_name      = params["rest_name"]
    restaurant_address   = params["rest_add"]
    restaurant_latitude  = params["rest_lat"]
    restaurant_longitude = params["rest_lng"]
    favorite = current_user.favorites.find_by(restaurant_name: restaurant_name, restaurant_address: restaurant_address)
    @restaurant = { "name" => restaurant_name, "address" => restaurant_address, "latitude" => restaurant_latitude, "longitude" => restaurant_longitude }
    if favorite.present?
      favorite.destroy
      flash[:success] = "お気に入りから削除しました。"
    else
      flash[:danger] = "お気に入りから削除出来ませんでした。"
    end
    redirect_to search_url(rest: @restaurant)
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  require 'net/http'

  def index
    if freeword = params[:freeword] 
      address = params[:address]
      keyid = ENV["key_gnavi"]
      params_1 = URI.encode_www_form({keyid: keyid})
      params_2 = URI.encode_www_form({freeword: freeword})
      params_3 = URI.encode_www_form({address: address})
      uri = URI.parse("https://api.gnavi.co.jp/RestSearchAPI/v3/?#{params_1}&#{params_2}&#{params_3}&hit_per_page=100")
      response = Net::HTTP.get_response(uri)
      results = JSON.parse(response.body)
      if results["rest"]
        @count=results["total_hit_count"]
        restaurants = results["rest"]
        @restaurants = Kaminari.paginate_array(restaurants).page(params[:page]).per(5)
      else
        flash[:danger] = "条件に一致する結果は見つかりませんでした。"
        redirect_to root_path
      end
    end
  end

  def show
    @restaurant = params["rest"]
    @key = ENV["key_map"]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @favorites = Favorite.where(user_id: @user.id)
  end

  def index
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div id="footer_inner">
    <p>Copyright GourmetApp 2020 All Rights Reserved</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
    <p>
      <%= link_to "GourmetApp", root_path %>
    </p>
    <nav>
      <ul>
        <li><%= link_to "トップ", root_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "ユーザー一覧", users_path %></li>
          <li><%= link_to current_user.username, user_path(current_user) %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "ログイン", new_user_session_path %></li>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GourmetApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="clear"></div>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <div class="clear"></div>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/searches/_search_form.html.erb
<div id="article_wrap">
  <%= form_with url: root_path, method: :get, local: true do |f| %>
    <p>
      <%= f.text_field :freeword, class: "search_form", placeholder: "キーワードを入力してください" %>
    </p>
    <p>
      <%= f.select :address, Ride.ride_areas.keys, {} %>
    </p>
    <%= f.submit "検索" %>
  <% end %>
</div>

app/views/searches/index.html.erb
<%= render 'search_form' %>

<div id="article_wrap">
  <% if @restaurants %>
    <p>
      <%= @count %>件見つかりました。
    </p>
    <% if @count > 100 %>
      <p>
        上位100件を表示しています。
      </p>
    <% end %>
    <% @restaurants.each do |restaurant| %>
      <p>
        レストラン名：<%= link_to restaurant["name"], search_path(rest: restaurant) %>
      </p>
      <p>
        <%= image_tag(restaurant["image_url"]["shop_image1"]) %>
        <%= image_tag(restaurant["image_url"]["shop_image2"]) %>
      </p>
    <% end %>
    <%= paginate @restaurants, class: "paginate" %>
  <% end %>
</div>

app/views/searches/show.html.erb
<p>
  レストラン名：<%= @restaurant["name"] %>
</p>
<p>
<p>
  住所：<%= @restaurant["address"] %>
  <script type="text/javascript">
    function initMap() {

      var test ={ lat: <%= @restaurant["latitude"] %>, lng: <%= @restaurant["longitude"] %> };
      var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 15, 
                center: test
                });
      var transitLayer = new google.maps.TransitLayer();
      transitLayer.setMap(map);

      var contentString = '住所：<%= @restaurant["address"] %>';
      var infowindow = new google.maps.InfoWindow({
                       content: contentString
                       });

      var marker = new google.maps.Marker({
                   position:test,
                   map: map,
                   title: contentString
                   });

      marker.addListener('click', function() {
        infowindow.open(map, marker);
      });
    }
  </script>

  <script async defer
                src='https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= @key %>&callback=initMap'>
  </script>
  <style type="text/css">
  #map { height: 200px;
         width: 70%;}
  </style>

  <div id="map"></div>
</p>
<p>
  <% if current_user.present? %>
    <% if Favorite.find_by(restaurant_name: @restaurant["name"], restaurant_address: @restaurant["address"], user_id: current_user) %>
      <%= link_to "お気に入り削除", favorites_path(rest_add: @restaurant["address"], rest_name: @restaurant["name"], rest_lat: @restaurant["latitude"], rest_lng: @restaurant["longitude"]), method: :delete %>
    <% else %>
      <%= link_to "お気に入り登録", favorites_path(rest_add: @restaurant["address"], rest_name: @restaurant["name"], rest_lat: @restaurant["latitude"], rest_lng: @restaurant["longitude"]), method: :post %>
    <% end %>
  <% end %>
</p>



app/views/users/index.html.erb
<% @users.each do |user| %>
  <p>
    <%= link_to user.username, user %>
  </p>
<% end %>

app/views/users/show.html.erb
<%= @user.username %>さんのお気に入り一覧
<% @favorites.each do |favorite| %>
  <p>
    <%= favorite.restaurant_name %>
  </p>
  <p>
    <%= favorite.restaurant_address %>
  </p>
<% end %>